project:
  type: website
  title: "MC Research Methods: Open Methods Hub"
  output-dir: docs
  render:
    - "*.qmd"
    - "modules/**/*.qmd"
    - "resources/*.qmd"
    - "workbook/*.qmd"

website:
  title: "Open Methods Hub"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Syllabus"
        menu:
          - text: "MC 451 (Spring 2026)"
            href: syllabus.qmd
          - text: "MC 501 (Fall 2026)"
            href: mc501-syllabus.qmd
      - text: "Phases"
        menu:
          - text: "Phase I: The Journalist"
            href: modules/01_journalist/index.qmd
          - text: "Phase II: The Architect"
            href: modules/02_architect/index.qmd
          - text: "Phase III: The Builder"
            href: modules/03_builder/index.qmd
          - text: "Phase IV: The Analyst"
            href: modules/04_analyst/index.qmd
          - text: "Practice: Pokemon Wrangling"
            href: modules/04_analyst/practice-wrangling.qmd
          - text: "Phase V: The Publisher"
            href: modules/05_publisher/index.qmd
      - text: "Workbook"
        href: workbook/index.qmd
      - text: "Textbook Preview"
        href: textbook-preview.qmd
      - text: "Methods Vault"
        href: methods-vault.qmd
      - text: "Resources"
        href: resources/index.qmd

  sidebar:
    - title: "R Workbook"
      style: "docked"
      contents:
        - workbook/index.qmd
        - section: "Chapters"
          contents:
            - workbook/01-codebook.qmd
            - workbook/02-data-collection.qmd
            - workbook/03-meet-r.qmd
            - workbook/04-data-wrangling.qmd
            - workbook/05-describing-data.qmd
            - workbook/06-inferencing-data.qmd
            - workbook/07-publishing.qmd
        - section: "Appendices"
          contents:
            - workbook/appendix-a-reference.qmd
            - workbook/appendix-b-glossary.qmd

format:
  html:
    theme: [cosmo, custom-styling.scss]
    toc: true
    code-fold: false
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
